/* tests/test_chain_compile.c — "Move Log -> Compile -> Constant Rules -> Derive Address"
 *
 * CLAIM under test: a chain of affine-modular hops  f(i) = (a*i + b) mod N
 * collapses into ONE closed form, so the runtime carries a constant-size
 * descriptor instead of replaying the log (and instead of a per-element table).
 *
 * The collapse is GUARANTEED when the moduli are NESTED, N(j+1) | N(j):
 * then (u mod N1) mod N2 == u mod N2 for every u. Nesting is SUFFICIENT, not
 * necessary -- degenerate chains collapse by coincidence (N1=2, a1=4, N2=4,
 * a2=1 collapses because a1*i is always even) -- so chain_check() uses the
 * conservative test and refuses the remainder. Over-refusing is the safe
 * direction here: an EXPANDING hop that slipped through would emit a
 * descriptor that looks like a clean bijection while pointing at slots the
 * chain never visited. That is the beam_carry_xfield shape, and it is why
 * chain_compile() refuses rather than trusting (T4). T7 shows the zero-storage
 * way to keep a reduce hop reversible: carry the quotient, which was never
 * thrown away in the first place.
 *
 * Why generated bytes are a complete proof here, not a weaker one:
 * every hop is value-blind -- it never reads the byte it moves (doctrine
 * #6192) -- so the roundtrip result cannot depend on byte content. A proof
 * over generated bytes therefore covers all byte arrays, real GGUF included.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../core/kis_codec_v6.h"
#include "../core/geo_tess_wiring.h"

typedef struct { uint32_t a, b, n; } Hop;   /* one hop: (a*i + b) mod n */
typedef struct { uint32_t A, B, N; } Desc;  /* compiled: constant size    */

typedef enum { COMPILE_OK = 0, COMPILE_NOT_NESTED = 1 } CompileStatus;

/* raw composition, no validity check */
static Desc chain_fold(const Hop *h, int k) {
    Desc d = { 1u, 0u, h[0].n };
    for (int j = 0; j < k; j++) {
        d.A = (uint32_t)(((uint64_t)h[j].a * d.A) % h[j].n);
        d.B = (uint32_t)(((uint64_t)h[j].a * d.B + h[j].b) % h[j].n);
        d.N = h[j].n;
    }
    return d;
}

/* Conservative: nested moduli guarantee the collapse. Chains that collapse by
 * other coincidences are refused too -- over-refusing is the safe direction. */
static CompileStatus chain_check(const Hop *h, int k) {
    for (int j = 1; j < k; j++)
        if ((h[j - 1].n % h[j].n) != 0) return COMPILE_NOT_NESTED;
    return COMPILE_OK;
}

/* Refuses to emit a descriptor for a chain that would lose a hop silently. */
static Desc chain_compile(const Hop *h, int k, CompileStatus *st) {
    CompileStatus s = chain_check(h, k);
    if (st) *st = s;
    if (s != COMPILE_OK) { Desc z = { 0u, 0u, 0u }; return z; }
    return chain_fold(h, k);
}

static uint32_t chain_naive(const Hop *h, int k, uint32_t i) {
    for (int j = 0; j < k; j++)
        i = (uint32_t)(((uint64_t)h[j].a * i + h[j].b) % h[j].n);
    return i;
}

static uint32_t desc_apply(Desc d, uint32_t i) {
    return (uint32_t)(((uint64_t)d.A * i + d.B) % d.N);
}

/* modular inverse by extended euclid; requires gcd(a, m) == 1 */
static uint32_t mod_inv(uint32_t a, uint32_t m) {
    int64_t t = 0, newt = 1, r = (int64_t)m, newr = (int64_t)a % (int64_t)m;
    while (newr != 0) {
        int64_t q = r / newr, tmp;
        tmp = t - q * newt; t = newt; newt = tmp;
        tmp = r - q * newr; r = newr; newr = tmp;
    }
    if (t < 0) t += (int64_t)m;
    return (uint32_t)t;
}

static uint32_t desc_unapply(uint32_t Ainv, Desc d, uint32_t j) {
    uint32_t t = (j + d.N - (d.B % d.N)) % d.N;
    return (uint32_t)(((uint64_t)Ainv * t) % d.N);
}

int main(void) {
    int pass = 0, fail = 0;
#define OK(c) do { if (c) { pass++; } else { fail++; printf("FAIL line %d\n", __LINE__); } } while (0)

    const uint32_t N = V6_SLOTS;   /* 20736 */

    /* T1: repo hop v6_slot is invertible BY RULE (mod inverse), no table.
     *     This is the invariant that makes roundtrip possible at all. */
    {
        uint32_t inv = mod_inv(V6_STRIDE, N);
        int bijective = 1;
        for (uint32_t i = 0; i < N; i++)
            if (desc_unapply(inv, (Desc){ V6_STRIDE, 0u, N }, v6_slot(i)) != i) { bijective = 0; break; }
        OK(bijective);
    }

    /* T2: NESTED REDUCING chain 20736 -> 5184 -> 1296 -> 144.
     *     Load-bearing claim: compiled == naive at EVERY position. */
    {
        Hop h[4] = { { 37u, 1u, 20736u }, { 5u, 3u, 5184u },
                     { 7u, 7u, 1296u },  { 11u, 11u, 144u } };
        CompileStatus st;
        Desc d = chain_compile(h, 4, &st);
        int same = 1;
        for (uint32_t i = 0; i < N; i++)
            if (desc_apply(d, i) != chain_naive(h, 4, i)) { same = 0; break; }
        printf("nested: A=%u B=%u N=%u\n", d.A, d.B, d.N);
        OK(st == COMPILE_OK);
        OK(same);
    }

    /* T3: CONSTANT-N chain, 4 distinct coprime strides, same 20736 domain.
     *     Collapse holds AND the composed map stays a bijection. */
    {
        Hop h[4] = { { 37u, 1u, N }, { 5u, 3u, N }, { 7u, 7u, N }, { 11u, 11u, N } };
        CompileStatus st;
        Desc d = chain_compile(h, 4, &st);
        int same = 1, bij = 1;
        uint32_t Ainv = mod_inv(d.A, d.N);
        for (uint32_t i = 0; i < N; i++)
            if (desc_apply(d, i) != chain_naive(h, 4, i)) { same = 0; break; }
        for (uint32_t i = 0; i < N; i++)
            if (desc_unapply(Ainv, d, desc_apply(d, i)) != i) { bij = 0; break; }
        printf("constant-N: A=%u B=%u N=%u\n", d.A, d.B, d.N);
        OK(st == COMPILE_OK);
        OK(same);
        OK(bij);
    }

    /* T4: the guard must FIRE on an expanding chain -- and it is not vacuous:
     *     the descriptor chain_fold() would have produced really was wrong,
     *     and looked like a clean bijection while being it. */
    {
        Hop h[2] = { { 37u, 1u, 144u }, { 5u, 1u, N } };
        CompileStatus st;
        Desc d = chain_compile(h, 2, &st);
        Desc wrong = chain_fold(h, 2);
        int differs = 0;
        for (uint32_t i = 0; i < N; i++)
            if (desc_apply(wrong, i) != chain_naive(h, 2, i)) { differs = 1; break; }
        OK(st == COMPILE_NOT_NESTED);
        OK(d.A == 0u && d.N == 0u);          /* refused => no usable descriptor */
        OK(differs);                         /* the refusal was warranted */

        /* returning to a wide modulus is still an expansion: 12 % 144 != 0 */
        Hop r[3] = { { 37u, 1u, 144u }, { 5u, 3u, 12u }, { 11u, 7u, 144u } };
        OK(chain_check(r, 3) == COMPILE_NOT_NESTED);

        printf("guard: refused expanding chain (%u->%u) and (%u->%u->%u); unchecked fold would be A=%u N=%u\n",
               h[0].n, h[1].n, r[0].n, r[1].n, r[2].n, wrong.A, wrong.N);
    }

    /* T5: byte roundtrip through the compiled resolver and back -- memcmp 100%. */
    {
        Hop h[4] = { { 37u, 1u, N }, { 5u, 3u, N }, { 7u, 7u, N }, { 11u, 11u, N } };
        Desc d = chain_compile(h, 4, NULL);
        uint32_t Ainv = mod_inv(d.A, d.N);
        const uint32_t SB = 64;
        size_t bytes = (size_t)N * SB;
        uint8_t *src = (uint8_t *)malloc(bytes);
        uint8_t *mid = (uint8_t *)malloc(bytes);
        uint8_t *out = (uint8_t *)malloc(bytes);
        if (!src || !mid || !out) { printf("FAIL alloc\n"); fail++; }
        else {
            uint32_t s = 0x12345678u;                 /* xorshift: non-trivial bytes */
            for (size_t i = 0; i < bytes; i++) {
                s ^= s << 13; s ^= s >> 17; s ^= s << 5;
                src[i] = (uint8_t)(s >> 24);
            }
            for (uint32_t i = 0; i < N; i++)
                memcpy(mid + (size_t)desc_apply(d, i) * SB, src + (size_t)i * SB, SB);
            for (uint32_t j = 0; j < N; j++)
                memcpy(out + (size_t)desc_unapply(Ainv, d, j) * SB, mid + (size_t)j * SB, SB);
            OK(memcmp(out, src, bytes) == 0);
            free(src); free(mid); free(out);
        }
    }

    /* T6: descriptor is CONSTANT SIZE -- 4-hop and 64-hop chains compile to
     *     the same state. This is "no table" made mechanical: the log grows,
     *     the runtime artifact does not. */
    {
        Hop h[64];
        for (int j = 0; j < 64; j++) { h[j].a = (uint32_t)(37 + 6 * j); h[j].b = (uint32_t)(j + 1); h[j].n = N; }
        int coprime = 1;
        for (int j = 0; j < 64; j++) if (mod_inv(h[j].a, N) == 0) coprime = 0;   /* fails loud */
        OK(coprime);
        Desc d4 = chain_compile(h, 4, NULL);
        Desc d64 = chain_compile(h, 64, NULL);
        OK(sizeof(Desc) == 12);
        OK(d4.N == d64.N);
        printf("descriptor: %u B for 4 hops, %u B for 64 hops (log = %u steps)\n",
               (unsigned)sizeof(Desc), (unsigned)sizeof(Desc), 64u);
    }

    /* T7: the free quotient. A reduce hop into a 144-wide window is reversible
     *     at ZERO extra storage, because the quotient was never discarded --
     *     it is the other half of the address. flat = q*W + r, W = TESS_CELLS
     *     = 144, the same width geo_tess_wiring.h splits on. Apply the chain to
     *     the low digit only; (y, q) must then carry all 20736 values. */
    {
        const uint32_t W = TESS_CELLS;                       /* 144 = GEO_TOWER */
        Hop h[3] = { { 37u, 1u, N }, { 5u, 3u, 1152u }, { 11u, 7u, W } };
        CompileStatus st;
        Desc d = chain_compile(h, 3, &st);
        uint32_t Ainv = mod_inv(d.A, d.N);
        uint8_t *seen = (uint8_t *)calloc(N, 1);
        int collision = 0, wrong = 0, disagree = 0, distinct_y = 0;
        uint32_t yseen[TESS_CELLS];
        memset(yseen, 0, sizeof(yseen));
        if (!seen) { printf("FAIL alloc\n"); fail++; }
        else {
            for (uint32_t i = 0; i < N; i++) {
                uint32_t q = i / W, r = i % W;              /* one divide: both halves */
                uint32_t y = desc_apply(d, r);
                uint32_t r_back = desc_unapply(Ainv, d, y);
                if (q * W + r_back != i) wrong = 1;
                if (seen[q * W + y]) collision = 1;
                seen[q * W + y] = 1;
                if (!yseen[y]) { yseen[y] = 1; distinct_y++; }
                /* the split must agree with the repo's own inverse pair */
                uint32_t te, cu, lo;
                flat_to_tess(i, &te, &cu, &lo);
                if (tess_to_flat(te, cu, lo) != i) disagree = 1;
            }
            free(seen);
        }
        OK(st == COMPILE_OK);
        OK(!wrong && !collision && !disagree);
        /* y alone lost the information -- exactly W distinct values, not 20736 */
        OK(distinct_y == W);
        printf("free quotient: W=%u  (y,q) injective over %u, y alone has %u values, 0 extra B\n",
               W, N, distinct_y);
    }

    printf("%d passed, %d failed\n", pass, fail);
    return fail ? 1 : 0;
}
