"""gen_goldberg_nbr.py — derive GP(4,0) dual adjacency from icosa combinatorics.

Method (exact, integer-indexed; floats only in discovery, never emitted):
  1. Icosa tables from 12 vertices (nearest-neighbor = edge; equilateral
     triples = faces). Verified: 30 edges x2 faces, degree 5, Euler 2.
  2. Geodesic(4,0) triangulation per face in barycentric ints (i+j+k=4):
     15 lattice points/face; boundary points unified by identity keys
     (corner = vertex id; edge point = (edge_id, dist-from-min-endpoint)).
  3. Triangulation adjacency = unit lattice steps (6 dirs) within each face,
     deduplicated across shared points.
  4. Dual faces: corners 0..11 (pentagons), edge points 12..101
     (12 + edge_id*3 + (k-1)), face interiors 102..161.
     Dual neighbors = triangulation adjacency, both directions.
Checks (fail loudly): corner degree 5, others 6; symmetry; incidence sum
12*5+150*6 = 960 = 2*480; split 12/90/60.
Emits: C table fragment for core/geo_goldberg_nbr.h (stdout).
"""
import math
import itertools
from collections import defaultdict

phi = (1 + 5 ** 0.5) / 2
V = [(0, 1, phi), (0, 1, -phi), (0, -1, phi), (0, -1, -phi),
     (1, phi, 0), (1, -phi, 0), (-1, phi, 0), (-1, -phi, 0),
     (phi, 0, 1), (-phi, 0, 1), (phi, 0, -1), (-phi, 0, -1)]


def d2(a, b):
    return sum((x - y) ** 2 for x, y in zip(a, b))


ds = sorted(set(round(d2(a, b), 6) for a, b in itertools.combinations(V, 2)))
E2 = ds[0]
edges = [p for p in itertools.combinations(range(12), 2)
         if abs(d2(V[p[0]], V[p[1]]) - E2) < 1e-6]
assert len(edges) == 30
EID = {e: i for i, e in enumerate(edges)}
faces = []
for t in itertools.combinations(range(12), 3):
    a, b, c = t
    if all(abs(d2(V[x], V[y]) - E2) < 1e-6 for x, y in [(a, b), (b, c), (a, c)]):
        faces.append(t)
assert len(faces) == 20

DIRS = [(1, -1, 0), (-1, 1, 0), (1, 0, -1),
        (-1, 0, 1), (0, 1, -1), (0, -1, 1)]


# rebuild with proper face-interior keys (need face id): do per-face below
adj = defaultdict(set)
pt_index = {}
f_interior = {}  # (face_id, i, j) insertion order -> idx 0..2


def get_idx(key):
    if key not in pt_index:
        pt_index[key] = len(pt_index)
    return pt_index[key]


for fi, (A, B, C) in enumerate(faces):
    lat = {}
    for i in range(5):
        for j in range(5 - i):
            k = 4 - i - j
            if (i, j, k) == (4, 0, 0):
                key = ('c', A)
            elif (i, j, k) == (0, 4, 0):
                key = ('c', B)
            elif (i, j, k) == (0, 0, 4):
                key = ('c', C)
            elif k == 0:
                a, bb = (A, B) if A < B else (B, A)
                d = j if A < B else i
                key = ('e', EID[(a, bb)], d)
            elif j == 0:
                a, bb = (A, C) if A < C else (C, A)
                d = k if A < C else i
                key = ('e', EID[(a, bb)], d)
            elif i == 0:
                a, bb = (B, C) if B < C else (C, B)
                d = k if B < C else j
                key = ('e', EID[(a, bb)], d)
            else:
                key = ('f', fi, i, j)
            lat[(i, j, k)] = get_idx(key)
    for b, u in lat.items():
        for d in DIRS:
            t = (b[0] + d[0], b[1] + d[1], b[2] + d[2])
            if t in lat:
                adj[u].add(lat[t])

print('lattice points:', len(pt_index))
degs = sorted(set(len(v) for v in adj.values()))
print('degrees present:', degs)
assert len(pt_index) == 162, len(pt_index)
n5 = sum(1 for v in adj.values() if len(v) == 5)
n6 = sum(1 for v in adj.values() if len(v) == 6)
print('deg5:', n5, 'deg6:', n6)
assert (n5, n6) == (12, 150)
assert sum(len(v) for v in adj.values()) == 960

# dual ids: corners 0..11; edge (eid,k) -> 12+eid*3+(k-1); interior per face
dual_of = {}
for key, u in pt_index.items():
    if key[0] == 'c':
        dual_of[u] = key[1]
    elif key[0] == 'e':
        _, eid, k = key
        assert 1 <= k <= 3
        dual_of[u] = 12 + eid * 3 + (k - 1)
edge_used = set()
f_int = defaultdict(list)
for key, u in pt_index.items():
    if key[0] == 'f':
        f_int[key[1]].append(u)
for fi in range(20):
    assert len(f_int[fi]) == 3, (fi, len(f_int[fi]))
    for t, u in enumerate(sorted(f_int[fi])):
        dual_of[u] = 102 + fi * 3 + t
assert sorted(dual_of.values()) == list(range(162))

nbr = {}
for u, vs in adj.items():
    nbr[dual_of[u]] = sorted(dual_of[v] for v in vs)
# symmetry + degrees from table side
for f, vs in nbr.items():
    for g in vs:
        assert f in nbr[g], (f, g)
    want = 5 if f < 12 else 6
    assert len(vs) == want, (f, len(vs))
assert all(g != f and 0 <= g < 162 for f, vs in nbr.items() for g in vs)
print('symmetric, degrees ok, incidence =',
      sum(len(v) for v in nbr.values()))

lines = ['/* generated by tools/gen_goldberg_nbr.py — DO NOT HAND-EDIT */',
         'static const uint8_t GP_NBR[162][6] = {']
for f in range(162):
    vs = nbr[f] + [255] * (6 - len(nbr[f]))
    lines.append('    {%s},%s' % (','.join(
        ('%3d' % v) for v in vs), ' /* %d: %s */' % (
            f, 'pent' if f < 12 else 'hex')))
lines.append('};')
print('\n'.join(lines))
