// Compare 3 Whisper models: tiny.en vs base vs small
// Shows transcript differences + word-level timing comparison

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#define MAX_WORDS 500
#define MAX_LEN 256

typedef struct {
    char text[MAX_LEN];
    float t0, t1;  // start/end time in seconds
    int word_idx;
} Word;

// Parse whisper output lines: [00:00:01.230 --> 00:00:03.450]   text
int parse_output(const char *filename, Word *words, int *n_words) {
    FILE *fp = fopen(filename, "r");
    if (!fp) return -1;
    
    *n_words = 0;
    char line[1024];
    
    while (fgets(line, sizeof(line), fp) && *n_words < MAX_WORDS) {
        // Parse timestamp
        int h0, m0, s0, ms0, h1, m1, s1, ms1;
        if (sscanf(line, "[%d:%d:%d.%d --> %d:%d:%d.%d]",
                   &h0, &m0, &s0, &ms0, &h1, &m1, &s1, &ms1) == 8) {
            float t0 = h0 * 3600 + m0 * 60 + s0 + ms0 / 1000.0f;
            float t1 = h1 * 3600 + m1 * 60 + s1 + ms1 / 1000.0f;
            
            // Extract text (after the last "]")
            char *text = strrchr(line, ']');
            if (text) {
                text++;  // skip ']'
                while (*text == ' ') text++;  // skip spaces
                
                // Remove trailing newline
                char *nl = strchr(text, '\n');
                if (nl) *nl = '\0';
                
                // Skip empty lines
                if (strlen(text) > 0) {
                    strncpy(words[*n_words].text, text, MAX_LEN - 1);
                    words[*n_words].t0 = t0;
                    words[*n_words].t1 = t1;
                    words[*n_words].word_idx = *n_words;
                    (*n_words)++;
                }
            }
        }
    }
    
    fclose(fp);
    return 0;
}

// Simple Levenshtein distance
int levenshtein(const char *a, const char *b) {
    int la = strlen(a), lb = strlen(b);
    int d[256][256];
    
    for (int i = 0; i <= la; i++) d[i][0] = i;
    for (int j = 0; j <= lb; j++) d[0][j] = j;
    
    for (int i = 1; i <= la; i++) {
        for (int j = 1; j <= lb; j++) {
            int cost = (a[i-1] == b[j-1]) ? 0 : 1;
            int del = d[i-1][j] + 1;
            int ins = d[i][j-1] + 1;
            int sub = d[i-1][j-1] + cost;
            d[i][j] = del < ins ? (del < sub ? del : sub) : (ins < sub ? ins : sub);
        }
    }
    return d[la][lb];
}

int main(void) {
    Word tiny[MAX_WORDS], base[MAX_WORDS], small[MAX_WORDS];
    int n_tiny, n_base, n_small;
    
    // Run whisper on each model
    printf("=== RUNNING WHISPER MODELS ===\n");
    printf("Model: tiny.en (39M), base (142M), small (461M)\n\n");
    
    // We'll parse from files generated by shell commands
    // For now, use hardcoded output from previous runs
    
    // tiny.en transcript (15 segments)
    const char *tiny_text[] = {
        "So if you look at an X-ray of a broken arm,",
        "it's, well, there's zero ambiguity.",
        "Yeah, you see the line.",
        "Exactly.",
        "You see that jagged white line on the film",
        "and the doctor just points to it and says,",
        "you know, there's the fracture.",
        "It's entirely binary.",
        "The system is either intact or it's broken.",
        "Right, and as human beings, we kind of crave that.",
        "It's comforting when a complex system",
        "can be diagnosed with just a single glance.",
        "We really do.",
        "But the moment you step out of a doctor's office",
        "and into the world."
    };
    float tiny_t0[] = {0.0, 3.32, 6.12, 7.2, 8.04, 10.08, 11.76, 13.28, 15.24, 18.24, 20.76, 23.08, 25.2, 26.48, 29.24};
    float tiny_t1[] = {3.32, 6.12, 7.2, 8.04, 10.08, 11.76, 13.28, 15.24, 18.24, 20.76, 23.08, 25.2, 26.48, 29.24, 30.28};
    n_tiny = 15;
    
    // base transcript (15 segments)
    const char *base_text[] = {
        "- So if you look at an x-ray of a broken arm,",
        "it's, well, there's zero ambiguity, right?",
        "- Yeah, you see the line.",
        "- Exactly, you see that jagged white line on the film",
        "and the doctor just points to it and says,",
        "you know, there's the fracture.",
        "It's entirely binary.",
        "The system is either intact or it's broken.",
        "- Right, and as human beings, we kind of crave that.",
        "It's comforting when a complex system",
        "can be diagnosed with just a single glance.",
        "- We really do.",
        "But the moment you step out of a doctor's office",
        "and into the world."
    };
    float base_t0[] = {0.0, 3.32, 6.04, 7.16, 9.96, 11.8, 13.28, 15.24, 18.24, 20.76, 23.08, 25.2, 26.48, 29.24};
    float base_t1[] = {3.32, 6.04, 7.16, 9.96, 11.8, 13.28, 15.24, 18.24, 20.76, 23.08, 25.2, 26.48, 29.24, 30.24};
    n_base = 14;
    
    // small transcript (14 segments)
    const char *small_text[] = {
        "- So if you look at an x-ray of a broken arm,",
        "it's, well, there's zero ambiguity, right?",
        "- Yeah, you see the line.",
        "- Exactly, you see that jagged white line on the film,",
        "and the doctor just points to it and says,",
        "you know, there's the fracture.",
        "It's entirely binary.",
        "The system is either intact or it's broken.",
        "- Right, and as human beings, we kind of crave that.",
        "It's comforting when a complex system",
        "can be diagnosed with just a single glance.",
        "- We really do.",
        "But the moment you step out of a doctor's office",
        "and into the world."
    };
    float small_t0[] = {0.0, 3.32, 6.4, 7.24, 10.0, 11.76, 13.28, 15.24, 18.24, 20.76, 23.08, 25.2, 26.48, 29.24};
    float small_t1[] = {3.32, 6.4, 7.24, 10.0, 11.76, 13.28, 15.24, 18.24, 20.76, 23.08, 25.2, 26.48, 29.24, 30.24};
    n_small = 14;
    
    // === COMPARISON ===
    printf("=== TRANSCRIPT COMPARISON ===\n\n");
    printf("tiny.en: %d segments\n", n_tiny);
    printf("base:    %d segments\n", n_base);
    printf("small:   %d segments\n\n", n_small);
    
    // Full text comparison
    char full_tiny[4096] = "", full_base[4096] = "", full_small[4096] = "";
    for (int i = 0; i < n_tiny; i++) { strcat(full_tiny, tiny_text[i]); strcat(full_tiny, " "); }
    for (int i = 0; i < n_base; i++) { strcat(full_base, base_text[i]); strcat(full_base, " "); }
    for (int i = 0; i < n_small; i++) { strcat(full_small, small_text[i]); strcat(full_small, " "); }
    
    printf("Edit distance (tiny vs base):  %d\n", levenshtein(full_tiny, full_base));
    printf("Edit distance (tiny vs small): %d\n", levenshtein(full_tiny, full_small));
    printf("Edit distance (base vs small): %d\n\n", levenshtein(full_base, full_small));
    
    // Word count comparison
    int wc_tiny = 0, wc_base = 0, wc_small = 0;
    for (int i = 0; i < n_tiny; i++) { char *p = tiny_text[i]; while (*p) { if (*p == ' ') wc_tiny++; p++; } wc_tiny++; }
    for (int i = 0; i < n_base; i++) { char *p = base_text[i]; while (*p) { if (*p == ' ') wc_base++; p++; } wc_base++; }
    for (int i = 0; i < n_small; i++) { char *p = small_text[i]; while (*p) { if (*p == ' ') wc_small++; p++; } wc_small++; }
    
    printf("Word count: tiny=%d, base=%d, small=%d\n\n", wc_tiny, wc_base, wc_small);
    
    // === TIMING COMPARISON ===
    printf("=== SEGMENT TIMING COMPARISON ===\n\n");
    printf("%-4s %-35s %-35s %-35s\n", "Seg", "tiny.en", "base", "small");
    printf("%-4s %-35s %-35s %-35s\n", "---", "-------", "----", "-----");
    
    int max_segs = n_tiny > n_base ? (n_tiny > n_small ? n_tiny : n_small) : (n_base > n_small ? n_base : n_small);
    
    for (int i = 0; i < max_segs && i < 15; i++) {
        char tiny_s[40] = "---", base_s[40] = "---", small_s[40] = "---";
        
        if (i < n_tiny) {
            char *t = tiny_text[i];
            if (strlen(t) > 30) { strncpy(tiny_s, t, 27); strcat(tiny_s, "..."); }
            else strcpy(tiny_s, t);
        }
        if (i < n_base) {
            char *t = base_text[i];
            if (strlen(t) > 30) { strncpy(base_s, t, 27); strcat(base_s, "..."); }
            else strcpy(base_s, t);
        }
        if (i < n_small) {
            char *t = small_text[i];
            if (strlen(t) > 30) { strncpy(small_s, t, 27); strcat(small_s, "..."); }
            else strcpy(small_s, t);
        }
        
        printf("%-4d %-35s %-35s %-35s\n", i, tiny_s, base_s, small_s);
    }
    
    // === KEY DIFFERENCES ===
    printf("\n=== KEY DIFFERENCES ===\n\n");
    printf("1. tiny.en says 'zero ambiguity' (no 'right?')\n");
    printf("   base/small say 'zero ambiguity, right?'\n\n");
    printf("2. tiny.en splits: 'Exactly.' then new segment\n");
    printf("   base/small merge: 'Exactly, you see that jagged...'\n\n");
    printf("3. tiny.en has 15 segments, base/small have 14\n");
    printf("   tiny.en over-segments (splits 'Exactly' separately)\n\n");
    printf("4. Timing differences:\n");
    printf("   tiny.en: segment 2 starts at 6.12s\n");
    printf("   base:    segment 2 starts at 6.04s\n");
    printf("   small:   segment 2 starts at 6.40s\n");
    printf("   → 360ms difference between base and small!\n\n");
    
    printf("=== IMPLICATION FOR GEOMETRIC AUDIO CODEC ===\n\n");
    printf("Different STT models see DIFFERENT word boundaries:\n");
    printf("  - Same audio, different segment splits\n");
    printf("  - Same audio, different word counts\n");
    printf("  - Same audio, different timing (up to 360ms)\n\n");
    printf("This means:\n");
    printf("  - Word boundaries are NOT objective truth\n");
    printf("  - They depend on the model's 'opinion'\n");
    printf("  - Our address mapping must be model-independent\n");
    printf("  - OR: we must choose ONE model as ground truth\n\n");
    printf("→ Use base as reference (good balance of speed/quality)\n");
    printf("→ Small for validation when precision matters\n");
    printf("→ Tiny for real-time / resource-constrained\n");
    
    return 0;
}
